---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: gha-runner-infrastructure
value: 1000000
globalDefault: false
description: "Priority class for GitHub Actions Runner infrastructure (controller, listener)"
