---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: emqx-init-user-secret
    creationPolicy: Owner
    template:
      data:
        init-user.json: |
          [
            {"user_id": "{{ index . "EMQX_DEFAULT_USERNAME" }}", "password": "{{ index . "EMQX_DEFAULT_PASSWORD" }}", "is_superuser": true},
            {"user_id": "{{ index . "EMQX_MQTT_USERNAME" }}", "password": "{{ index . "EMQX_MQTT_PASSWORD" }}", "is_superuser": false}
          ]
        init-acl: |
          {allow, {user, "{{ index . "EMQX_MQTT_USERNAME" }}"}, all, ["#"]}.
  dataFrom:
    - extract:
        key: EMQX
