---
# yaml-language-server: $schema=https://json.schemastore.org/config

apiVersion: v1
kind: ConfigMap
metadata:
  name: tikv-pd-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: tikv-pd
        group: database
        url: tcp://tikv-pd.database.svc.cluster.local:2379
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
        ui:
          hide-url: true
          hide-hostname: true
