---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # LiteLLM
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}" # Must start with sk-
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}" # Must start with sk-
        UI_USERNAME: "{{ .LITELLM_UI_USERNAME }}"
        UI_PASSWORD: "{{ .LITELLM_UI_PASSWORD }}"
        # DOCS_URL: "{{ .LITELLM_DOCS_URL }}"
        QDRANT_API_BASE: http://qdrant:6333
        QDRANT_API_KEY: "{{ .QDRANT_API_KEY }}"
        # OIDC - Pocket ID Settings
        # AI APIs
        ## Anthropic
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        ## Deepseek
        DEEPSEEK_API_KEY: "{{ .DEEPSEEK_API_KEY }}"
        ## Groq - Multiple Models
        GROQ_API_KEY: "{{ .GROQ_API_KEY }}"
        ## OpenAI
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        ## Together.ai
        TOGETHERAI_API_KEY: "{{ .TOGETHERAI_API_KEY }}"
        ## xAI
        XAI_API_KEY: "{{ .XAI_API_KEY }}"

        ## Gemini
        GEMINI_API_KEY: "{{ .GEMINI_API_KEY }}"

        ## Mistral
        MISTRAL_API_KEY: "{{ .MISTRAL_API_KEY }}"
        # PostgreSQL Connection URL
        DATABASE_URL: "postgresql://{{ .POSTGRES_DB_USER_NAME }}:{{ .POSTGRES_DB_USER_PASSWORD }}@{{ .POSTGRES_DB_HOST }}:5432/{{ .POSTGRES_DB_NAME }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ai-keys
    - extract:
        key: litellm
    - extract:
        key: qdrant
    - extract:
        key: cloudnative-pg
