# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reading-glasses
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: reading-glasses-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: &dbUser "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        POSTGRES__HOST: *dbHost
        POSTGRES__MAINDB: *dbName
        POSTGRES__USER: *dbUser
        POSTGRES__PASSWORD: *dbPass
        POSTGRES__PORT: "5432"

        HARDCOVER_API_KEY: "{{ .HARDCOVER_API_KEY }}"
        GOODREADS_COOKIE: "{{ .GOODREADS_COOKIE }}"

  dataFrom:
    - extract:
        key: hardcover
    - extract:
        key: cloudnative-pg
    - extract:
        key: rreading-glasses
    - extract:
        key: goodreads
