---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-repo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: image-repo-secret
    template:
      # Opaque type with config.json for Kaniko builder
      type: Opaque
      data:
        config.json: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}",
                "username": "{{ .GHCR_USERNAME }}",
                "password": "{{ .GHCR_TOKEN }}"
              }
            }
          }
  data:
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: dify
        property: GHCR_USERNAME
    - secretKey: GHCR_TOKEN
      remoteRef:
        key: dify
        property: GHCR_TOKEN
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-pull-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: image-pull-secret
    template:
      # dockerconfigjson type for imagePullSecrets
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}",
                "username": "{{ .GHCR_USERNAME }}",
                "password": "{{ .GHCR_TOKEN }}"
              }
            }
          }
  data:
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: dify
        property: GHCR_USERNAME
    - secretKey: GHCR_TOKEN
      remoteRef:
        key: dify
        property: GHCR_TOKEN
