---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
  data:
    - secretKey: mqtt_user
      remoteRef:
        key: EMQX
        property: EMQX_MQTT_USERNAME
    - secretKey: mqtt_password
      remoteRef:
        key: EMQX
        property: EMQX_MQTT_PASSWORD
    - secretKey: zigbee_pan_id
      remoteRef:
        key: zigbee2mqtt
        property: CONFIG_PAN_ID
    - secretKey: zigbee_ext_pan_id
      remoteRef:
        key: zigbee2mqtt
        property: CONFIG_EXT_PAN_ID
    - secretKey: zigbee_network_key
      remoteRef:
        key: zigbee2mqtt
        property: CONFIG_NETWORK_KEY
