---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-web-automated
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: volsync
      namespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/calibre/calibre-web-automated
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 3m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_PUID: "2000"
      VOLSYNC_PGID: "2000"
      VOLSYNC_SCHEDULE_CEPH: "0 */4 * * *"
      VOLSYNC_SCHEDULE_MINIO: "45 */6 * * *"
      VOLSYNC_SCHEDULE_R2: "5 4 * * *"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-downloader
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/calibre/calibre-downloader
  components:
    - ../../../../components/gatus/guarded
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 10m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
