---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: surrealdb-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: surrealdb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .SURREALDB_ROOT_PASSWORD }}"
        username: "{{ .SURREALDB_ROOT_USER }}"
  dataFrom:
    - extract:
        key: surrealdb
