---
# yaml-language-server: $schema=https://json.schemastore.org/config
apiVersion: v1
kind: ConfigMap
metadata:
  name: surrealdb-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: surrealdb-http
        group: database
        url: http://surrealdb.database.svc.cluster.local:8000/health
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
        ui:
          hide-url: true
          hide-hostname: true
