---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: surrealdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: surrealdb
  podTargetLabels:
    - app.kubernetes.io/name
  podMetricsEndpoints:
    - port: http  # Port 8000
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
