---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/jetstream.nats.io/stream_v1beta2.json
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: events
spec:
  name: events
  subjects:
    - "events.>"
  storage: file
  replicas: 3
  retention: limits
  maxAge: 168h
  maxBytes: 5368709120
  discard: old
