---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./crunchy-userinit.yaml
  - ./crunchydata.yaml
  - ./coder.yaml
  - ./emqx-charts.yaml
  - ./external-dns.yaml
  - ./headlamp.yaml
  - ./angelnu-helm-charts.yaml
