---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rsshub
  namespace: &namespace selfhosted
spec:
  components:
    - ../../../../components/volsync/
    - ../../../../components/dragonfly
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/rsshub/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_SCHEDULE_CEPH: "20 */4 * * *"
      VOLSYNC_SCHEDULE_MINIO: "0 */6 * * *"
      VOLSYNC_SCHEDULE_R2: "25 4 * * *"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: system
    - name: dragonfly-operator
      namespace: database
    - name: rsshub-playwright
      namespace: *namespace
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rsshub-playwright
  namespace: &namespace selfhosted
spec:
  components:
    - ../../../../components/volsync/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/rsshub/playwright
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_SCHEDULE_CEPH: "25 */4 * * *"
      VOLSYNC_SCHEDULE_MINIO: "0 */6 * * *"
      VOLSYNC_SCHEDULE_R2: "30 4 * * *"
  prune: true
  retryInterval: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: system
    - name: dragonfly-operator
      namespace: database
  targetNamespace: *namespace
  timeout: 5m
  wait: false
