---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rsshub
  namespace: &namespace selfhosted
spec:
  components:
    - ../../../../components/volsync/
    - ../../../../components/dragonfly
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/rsshub/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: volsync-system
    - name: dragonfly-operator
      namespace: database
    - name: rsshub-playwright
      namespace: *namespace
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rsshub-playwright
  namespace: &namespace selfhosted
spec:
  components:
    - ../../../../components/volsync/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/selfhosted/rsshub/playwright
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: dragonfly-cluster
      namespace: database
  targetNamespace: *namespace
  timeout: 5m
  wait: false
