---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./anthropic.yaml
  - ./openai.yaml
  - ./deepseek.yaml
  - ./mistral.yaml
  - ./gemini.yaml
  - ./groq.yaml
  - ./togetherai.yaml
  - ./xai.yaml