---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xai-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: xai-secret
    template:
      data:
        Authorization: "{{ .XAI_API_KEY }}"
  dataFrom:
    - extract:
        key: ai-keys
---
# xai BAgentgatewayBackend (OpenAI-compatible)
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: xai
spec:
  ai:
    provider:
      openai:
        model: "grok-3-fast"
      host: api.x.ai
      port: 443
  policies:
    auth:
      secretRef:
        name: xai-secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: xai
spec:
  parentRefs:
    - name: internal
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /xai
    backendRefs:
    - name: xai
      group: agentgateway.dev
      kind: AgentgatewayBackend
